name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies and build
        run: |        	
          export ENABLE_MCP=true
          yarn install
          yarn build

      - name: Prepare standalone for deployment
        run: |
          cp -r public .next/standalone/
          mkdir -p .next/standalone/.next
          cp -r .next/static .next/standalone/.next/

      - name: Zip the standalone directory
        run: |
          zip -r release.zip .next/standalone

      - uses: actions/upload-artifact@v4
        with:
          name: release.zip
          path: release.zip

  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release.zip

      - name: SCP Transfer
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: release.zip
          target: /tmp/NextChat

      - name: Remote Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -ex
            source .profile
            mv /tmp/NextChat/release.zip release.zip            
            unzip -qq -o release.zip
            rm -r /tmp/NextChat release.zip
            pm2 reload NextChat
            echo "NextChat Updated successfully"
